NEI<-readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
subsetNEI<-subset(NEI,NEI$fips=="24510")
aggsubsetNEI<-aggregate(Emissions~year,subsetNEI,sum)
png("plot2.png",height=480,width = 480)
barplot(height=aggsubsetNEI$Emissions,names.arg = aggsubsetNEI$year,col="red",xlab="year",ylab="PM2.5 Emission in baltimorecity",main = "total PM2.5 Emission in Baltimore city")
dev.off()